[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"

# Environment variables for GitHub integration
# Note: Set these in Netlify UI under Site settings > Environment variables
# VITE_GITHUB_TOKEN = "your_github_personal_access_token"
# VITE_GITHUB_OWNER = "your_github_username"
# VITE_GITHUB_REPO = "your_repo_name"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.tailwindcss.com/3.4.1; style-src 'self' 'unsafe-inline'; connect-src 'self' https://api.github.com https://*.github.com; img-src 'self' data: https:; font-src 'self' data:; object-src 'none'; base-uri 'self'; form-action 'self';"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"